# coding: utf-8

"""
    Rapidata Asset API

    The API for the Rapidata Asset service

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt, StrictStr, field_validator
from typing import List, Optional
from typing_extensions import Annotated
from rapidata.api_client.models.create_validation_feedback_endpoint_input import CreateValidationFeedbackEndpointInput
from rapidata.api_client.models.flow_get_name_parameter import FlowGetNameParameter
from rapidata.api_client.models.query_validation_feedbacks_endpoint_paged_result_of_output import QueryValidationFeedbacksEndpointPagedResultOfOutput

from rapidata.api_client.api_client import ApiClient, RequestSerialized
from rapidata.api_client.api_response import ApiResponse
from rapidata.api_client.rest import RESTResponseType


class ValidationFeedbackApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def rapid_rapid_id_validation_feedback_get(
        self,
        rapid_id: Annotated[StrictStr, Field(description="The ID of the rapid to query feedbacks for.")],
        page: Annotated[Optional[StrictInt], Field(description="The 1-based page index.")] = None,
        page_size: Annotated[Optional[StrictInt], Field(description="The number of items per page.")] = None,
        sort: Annotated[Optional[List[StrictStr]], Field(description="Sort fields. Prefix with - for descending order (e.g. -created_at).")] = None,
        user_id: Annotated[Optional[FlowGetNameParameter], Field(description="Filter by user_id.")] = None,
        feedback: Annotated[Optional[FlowGetNameParameter], Field(description="Filter by feedback.")] = None,
        created_at: Annotated[Optional[FlowGetNameParameter], Field(description="Filter by created_at.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> QueryValidationFeedbacksEndpointPagedResultOfOutput:
        """Queries validation feedbacks for a rapid.


        :param rapid_id: The ID of the rapid to query feedbacks for. (required)
        :type rapid_id: str
        :param page: The 1-based page index.
        :type page: int
        :param page_size: The number of items per page.
        :type page_size: int
        :param sort: Sort fields. Prefix with - for descending order (e.g. -created_at).
        :type sort: List[str]
        :param user_id: Filter by user_id.
        :type user_id: FlowGetNameParameter
        :param feedback: Filter by feedback.
        :type feedback: FlowGetNameParameter
        :param created_at: Filter by created_at.
        :type created_at: FlowGetNameParameter
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._rapid_rapid_id_validation_feedback_get_serialize(
            rapid_id=rapid_id,
            page=page,
            page_size=page_size,
            sort=sort,
            user_id=user_id,
            feedback=feedback,
            created_at=created_at,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "QueryValidationFeedbacksEndpointPagedResultOfOutput",
            '400': "ValidationProblemDetails",
            '401': None,
            '403': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def rapid_rapid_id_validation_feedback_get_with_http_info(
        self,
        rapid_id: Annotated[StrictStr, Field(description="The ID of the rapid to query feedbacks for.")],
        page: Annotated[Optional[StrictInt], Field(description="The 1-based page index.")] = None,
        page_size: Annotated[Optional[StrictInt], Field(description="The number of items per page.")] = None,
        sort: Annotated[Optional[List[StrictStr]], Field(description="Sort fields. Prefix with - for descending order (e.g. -created_at).")] = None,
        user_id: Annotated[Optional[FlowGetNameParameter], Field(description="Filter by user_id.")] = None,
        feedback: Annotated[Optional[FlowGetNameParameter], Field(description="Filter by feedback.")] = None,
        created_at: Annotated[Optional[FlowGetNameParameter], Field(description="Filter by created_at.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[QueryValidationFeedbacksEndpointPagedResultOfOutput]:
        """Queries validation feedbacks for a rapid.


        :param rapid_id: The ID of the rapid to query feedbacks for. (required)
        :type rapid_id: str
        :param page: The 1-based page index.
        :type page: int
        :param page_size: The number of items per page.
        :type page_size: int
        :param sort: Sort fields. Prefix with - for descending order (e.g. -created_at).
        :type sort: List[str]
        :param user_id: Filter by user_id.
        :type user_id: FlowGetNameParameter
        :param feedback: Filter by feedback.
        :type feedback: FlowGetNameParameter
        :param created_at: Filter by created_at.
        :type created_at: FlowGetNameParameter
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._rapid_rapid_id_validation_feedback_get_serialize(
            rapid_id=rapid_id,
            page=page,
            page_size=page_size,
            sort=sort,
            user_id=user_id,
            feedback=feedback,
            created_at=created_at,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "QueryValidationFeedbacksEndpointPagedResultOfOutput",
            '400': "ValidationProblemDetails",
            '401': None,
            '403': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def rapid_rapid_id_validation_feedback_get_without_preload_content(
        self,
        rapid_id: Annotated[StrictStr, Field(description="The ID of the rapid to query feedbacks for.")],
        page: Annotated[Optional[StrictInt], Field(description="The 1-based page index.")] = None,
        page_size: Annotated[Optional[StrictInt], Field(description="The number of items per page.")] = None,
        sort: Annotated[Optional[List[StrictStr]], Field(description="Sort fields. Prefix with - for descending order (e.g. -created_at).")] = None,
        user_id: Annotated[Optional[FlowGetNameParameter], Field(description="Filter by user_id.")] = None,
        feedback: Annotated[Optional[FlowGetNameParameter], Field(description="Filter by feedback.")] = None,
        created_at: Annotated[Optional[FlowGetNameParameter], Field(description="Filter by created_at.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Queries validation feedbacks for a rapid.


        :param rapid_id: The ID of the rapid to query feedbacks for. (required)
        :type rapid_id: str
        :param page: The 1-based page index.
        :type page: int
        :param page_size: The number of items per page.
        :type page_size: int
        :param sort: Sort fields. Prefix with - for descending order (e.g. -created_at).
        :type sort: List[str]
        :param user_id: Filter by user_id.
        :type user_id: FlowGetNameParameter
        :param feedback: Filter by feedback.
        :type feedback: FlowGetNameParameter
        :param created_at: Filter by created_at.
        :type created_at: FlowGetNameParameter
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._rapid_rapid_id_validation_feedback_get_serialize(
            rapid_id=rapid_id,
            page=page,
            page_size=page_size,
            sort=sort,
            user_id=user_id,
            feedback=feedback,
            created_at=created_at,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "QueryValidationFeedbacksEndpointPagedResultOfOutput",
            '400': "ValidationProblemDetails",
            '401': None,
            '403': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _rapid_rapid_id_validation_feedback_get_serialize(
        self,
        rapid_id,
        page,
        page_size,
        sort,
        user_id,
        feedback,
        created_at,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'sort': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if rapid_id is not None:
            _path_params['rapidId'] = rapid_id
        # process the query parameters
        if page is not None:
            
            _query_params.append(('page', page))
            
        if page_size is not None:
            
            _query_params.append(('page_size', page_size))
            
        if sort is not None:
            
            _query_params.append(('sort', sort))
            
        if user_id is not None:
            
            _query_params.append(('user_id', user_id))
            
        if feedback is not None:
            
            _query_params.append(('feedback', feedback))
            
        if created_at is not None:
            
            _query_params.append(('created_at', created_at))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'OAuth2', 
            'OpenIdConnect', 
            'Bearer'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/rapid/{rapidId}/validation-feedback',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def rapid_rapid_id_validation_feedback_post(
        self,
        rapid_id: Annotated[StrictStr, Field(description="The ID of the rapid to provide feedback for.")],
        create_validation_feedback_endpoint_input: Annotated[CreateValidationFeedbackEndpointInput, Field(description="The feedback input.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Submits feedback for a validation rapid outcome.


        :param rapid_id: The ID of the rapid to provide feedback for. (required)
        :type rapid_id: str
        :param create_validation_feedback_endpoint_input: The feedback input. (required)
        :type create_validation_feedback_endpoint_input: CreateValidationFeedbackEndpointInput
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._rapid_rapid_id_validation_feedback_post_serialize(
            rapid_id=rapid_id,
            create_validation_feedback_endpoint_input=create_validation_feedback_endpoint_input,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '204': None,
            '400': "ValidationProblemDetails",
            '401': None,
            '403': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def rapid_rapid_id_validation_feedback_post_with_http_info(
        self,
        rapid_id: Annotated[StrictStr, Field(description="The ID of the rapid to provide feedback for.")],
        create_validation_feedback_endpoint_input: Annotated[CreateValidationFeedbackEndpointInput, Field(description="The feedback input.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Submits feedback for a validation rapid outcome.


        :param rapid_id: The ID of the rapid to provide feedback for. (required)
        :type rapid_id: str
        :param create_validation_feedback_endpoint_input: The feedback input. (required)
        :type create_validation_feedback_endpoint_input: CreateValidationFeedbackEndpointInput
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._rapid_rapid_id_validation_feedback_post_serialize(
            rapid_id=rapid_id,
            create_validation_feedback_endpoint_input=create_validation_feedback_endpoint_input,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '204': None,
            '400': "ValidationProblemDetails",
            '401': None,
            '403': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def rapid_rapid_id_validation_feedback_post_without_preload_content(
        self,
        rapid_id: Annotated[StrictStr, Field(description="The ID of the rapid to provide feedback for.")],
        create_validation_feedback_endpoint_input: Annotated[CreateValidationFeedbackEndpointInput, Field(description="The feedback input.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Submits feedback for a validation rapid outcome.


        :param rapid_id: The ID of the rapid to provide feedback for. (required)
        :type rapid_id: str
        :param create_validation_feedback_endpoint_input: The feedback input. (required)
        :type create_validation_feedback_endpoint_input: CreateValidationFeedbackEndpointInput
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._rapid_rapid_id_validation_feedback_post_serialize(
            rapid_id=rapid_id,
            create_validation_feedback_endpoint_input=create_validation_feedback_endpoint_input,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '204': None,
            '400': "ValidationProblemDetails",
            '401': None,
            '403': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _rapid_rapid_id_validation_feedback_post_serialize(
        self,
        rapid_id,
        create_validation_feedback_endpoint_input,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if rapid_id is not None:
            _path_params['rapidId'] = rapid_id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if create_validation_feedback_endpoint_input is not None:
            _body_params = create_validation_feedback_endpoint_input


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'OAuth2', 
            'OpenIdConnect', 
            'Bearer'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/rapid/{rapidId}/validation-feedback',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


