# This file is auto-generated by scripts/generate_settings.py
# Do not edit manually. Changes will be overwritten.
# To modify, update settings.json and re-run the generator.

from .no_shuffle import NoShuffleSetting
from .mute_video import MuteVideoSetting
from .free_text_minimum_characters import FreeTextMinimumCharactersSetting
from .free_text_max_characters import FreeTextMaxCharactersSetting
from .swap_context_instruction import SwapContextInstructionSetting
from .play_percentage_video import PlayPercentageVideoSetting
from .markdown import MarkdownSetting
from .allow_neither_both import AllowNeitherBothSetting
from .force_original_language import ForceOriginalLanguageSetting
from .no_mistake import NoMistakeSetting
from .disable_autoloop import DisableAutoloopSetting
from .no_instruction_display import NoInstructionDisplaySetting
from .keyboard_numeric import KeyboardNumericSetting
from .locate_max_points import LocateMaxPointsSetting
from .locate_min_points import LocateMinPointsSetting
from .compare_panorama import ComparePanoramaSetting
from .compare_equirectangular import CompareEquirectangularSetting
from .custom_setting import CustomSetting
from ._rapidata_setting import RapidataSetting
from .rapidata_settings import RapidataSettings
