# This file is auto-generated by scripts/generate_settings.py
# Do not edit manually. Changes will be overwritten.
# To modify, update settings.json and re-run the generator.

from __future__ import annotations

from rapidata.rapidata_client.settings._rapidata_setting import RapidataSetting


class AllowNeitherBothSetting(RapidataSetting):
    """
    Only for compare tasks. Enables an "Unsure" button that allows users to select neither or both options.

    The delay controls how many milliseconds before the unsure button appears.

    Args:
        delay_ms (int, optional): Delay in milliseconds before the unsure button appears. Defaults to 5000.
    """

    def __init__(self, delay_ms: int = 5000):
        if delay_ms < 0:
            raise ValueError(
                "The delay must be greater than or equal to 0 milliseconds."
            )
        super().__init__(key="compare_unsure", value=delay_ms)
