# This file is auto-generated by scripts/generate_settings.py
# Do not edit manually. Changes will be overwritten.
# To modify, update settings.json and re-run the generator.

from __future__ import annotations

from rapidata.rapidata_client.settings._rapidata_setting import RapidataSetting


class LocateMaxPointsSetting(RapidataSetting):
    """
    Sets the maximum number of points a user can place on a locate task. Once the limit is reached, no more points can be added.

    Args:
        value (int, optional): The maximum number of points allowed. Defaults to 3.
    """

    def __init__(self, value: int = 3):
        if value < 1:
            raise ValueError(
                "The maximum number of points must be at least 1."
            )
        super().__init__(key="locate_max_points", value=value)
