# coding: utf-8

"""
    Rapidata Asset API

    The API for the Rapidata Asset service

    The version of the OpenAPI document: 2026.07.24.1303-b3d1ec7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from rapidata.api_client.models.audience_status import AudienceStatus
from rapidata.api_client.models.boost_level import BoostLevel
from rapidata.api_client.models.i_audience_filter import IAudienceFilter
from rapidata.api_client.models.i_graduation_rule import IGraduationRule
from rapidata.api_client.models.retrieval_mode import RetrievalMode
from pydantic import ValidationError
from rapidata.api_client.lazy_model import LazyValidatedModel
from typing import Optional, Set
from typing_extensions import Self

class GetAudienceByIdEndpointOutput(LazyValidatedModel):
    """
    GetAudienceByIdEndpointOutput
    """ # noqa: E501
    id: StrictStr = Field(description="The unique identifier of the audience.")
    name: StrictStr = Field(description="The name of the audience.")
    description: Optional[StrictStr] = Field(default=None, description="The markdown-supported description of the audience.")
    status: AudienceStatus = Field(description="The current status of the audience.")
    qualified_user_count: StrictInt = Field(description="The number of users that have qualified for this audience.", alias="qualifiedUserCount")
    filters: List[IAudienceFilter]
    logo: Optional[StrictStr] = Field(default=None, description="The URL of the audience logo, if any.")
    created_at: datetime = Field(description="The timestamp when the audience was created.", alias="createdAt")
    owner_id: UUID = Field(description="The unique identifier of the audience owner.", alias="ownerId")
    owner_mail: StrictStr = Field(description="The email of the audience owner.", alias="ownerMail")
    organization_id: Optional[StrictStr] = Field(default=None, description="The id of the organization that owns the entity.", alias="organizationId")
    is_public: StrictBool = Field(description="Whether the audience is publicly visible.", alias="isPublic")
    is_distilling: StrictBool = Field(description="Whether the audience is currently distilling users.", alias="isDistilling")
    distilling_campaign_id: StrictStr = Field(description="The id of the distilling campaign associated with the audience.", alias="distillingCampaignId")
    min_graduated_for_distilling_boost: Optional[StrictInt] = Field(default=None, description="Minimum graduated users before disabling distilling boost.", alias="minGraduatedForDistillingBoost")
    min_distilling_for_global_boost: Optional[StrictInt] = Field(default=None, description="Minimum distilling users before disabling global boost.", alias="minDistillingForGlobalBoost")
    graduation_rule: IGraduationRule = Field(description="The rule this audience uses to graduate users — a score-threshold rule or a  task-accuracy rule.", alias="graduationRule")
    max_distilling_responses: Optional[StrictInt] = Field(default=None, description="Maximum responses before user exits the distilling campaign.", alias="maxDistillingResponses")
    drop_min_responses: Optional[StrictInt] = Field(default=None, description="Minimum responses before the drop score check applies.", alias="dropMinResponses")
    drop_score: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Score floor - users below this score exit the distilling campaign.", alias="dropScore")
    max_distilling_sessions: Optional[StrictInt] = Field(default=None, description="Maximum sessions before user exits the distilling campaign.", alias="maxDistillingSessions")
    inactivity_drop_days: Optional[StrictInt] = Field(default=None, description="Number of days of inactivity before a distilling user is dropped.", alias="inactivityDropDays")
    min_submission_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Minimum submission rate before a user is dropped.", alias="minSubmissionRate")
    min_sessions_for_submission_rate: Optional[StrictInt] = Field(default=None, description="Minimum number of sessions before the submission rate check applies.", alias="minSessionsForSubmissionRate")
    min_submission_rate_graduated: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Minimum submission rate for graduated users.", alias="minSubmissionRateGraduated")
    distilling_retrieval_mode: RetrievalMode = Field(description="The retrieval mode used by the distilling campaign to select rapids for users.", alias="distillingRetrievalMode")
    boost_level: BoostLevel = Field(description="The current boost level applied to the audience.", alias="boostLevel")
    random_admission_probability: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The probability of admitting a random user to the audience.", alias="randomAdmissionProbability")
    health: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The health score of the audience.")
    graduated: Optional[StrictInt] = Field(default=None, description="The number of graduated users.")
    dropped: Optional[StrictInt] = Field(default=None, description="The number of dropped users.")
    __properties: ClassVar[List[str]] = ["id", "name", "description", "status", "qualifiedUserCount", "filters", "logo", "createdAt", "ownerId", "ownerMail", "organizationId", "isPublic", "isDistilling", "distillingCampaignId", "minGraduatedForDistillingBoost", "minDistillingForGlobalBoost", "graduationRule", "maxDistillingResponses", "dropMinResponses", "dropScore", "maxDistillingSessions", "inactivityDropDays", "minSubmissionRate", "minSessionsForSubmissionRate", "minSubmissionRateGraduated", "distillingRetrievalMode", "boostLevel", "randomAdmissionProbability", "health", "graduated", "dropped"]

    # model_config is inherited from LazyValidatedModel


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetAudienceByIdEndpointOutput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in filters (list)
        _items = []
        if self.filters:
            for _item_filters in self.filters:
                if _item_filters:
                    _items.append(_item_filters.to_dict())
            _dict['filters'] = _items
        # override the default output from pydantic by calling `to_dict()` of graduation_rule
        if self.graduation_rule:
            _dict['graduationRule'] = self.graduation_rule.to_dict()
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if logo (nullable) is None
        # and model_fields_set contains the field
        if self.logo is None and "logo" in self.model_fields_set:
            _dict['logo'] = None

        # set to None if organization_id (nullable) is None
        # and model_fields_set contains the field
        if self.organization_id is None and "organization_id" in self.model_fields_set:
            _dict['organizationId'] = None

        # set to None if min_graduated_for_distilling_boost (nullable) is None
        # and model_fields_set contains the field
        if self.min_graduated_for_distilling_boost is None and "min_graduated_for_distilling_boost" in self.model_fields_set:
            _dict['minGraduatedForDistillingBoost'] = None

        # set to None if min_distilling_for_global_boost (nullable) is None
        # and model_fields_set contains the field
        if self.min_distilling_for_global_boost is None and "min_distilling_for_global_boost" in self.model_fields_set:
            _dict['minDistillingForGlobalBoost'] = None

        # set to None if max_distilling_responses (nullable) is None
        # and model_fields_set contains the field
        if self.max_distilling_responses is None and "max_distilling_responses" in self.model_fields_set:
            _dict['maxDistillingResponses'] = None

        # set to None if drop_min_responses (nullable) is None
        # and model_fields_set contains the field
        if self.drop_min_responses is None and "drop_min_responses" in self.model_fields_set:
            _dict['dropMinResponses'] = None

        # set to None if drop_score (nullable) is None
        # and model_fields_set contains the field
        if self.drop_score is None and "drop_score" in self.model_fields_set:
            _dict['dropScore'] = None

        # set to None if max_distilling_sessions (nullable) is None
        # and model_fields_set contains the field
        if self.max_distilling_sessions is None and "max_distilling_sessions" in self.model_fields_set:
            _dict['maxDistillingSessions'] = None

        # set to None if inactivity_drop_days (nullable) is None
        # and model_fields_set contains the field
        if self.inactivity_drop_days is None and "inactivity_drop_days" in self.model_fields_set:
            _dict['inactivityDropDays'] = None

        # set to None if min_submission_rate (nullable) is None
        # and model_fields_set contains the field
        if self.min_submission_rate is None and "min_submission_rate" in self.model_fields_set:
            _dict['minSubmissionRate'] = None

        # set to None if min_sessions_for_submission_rate (nullable) is None
        # and model_fields_set contains the field
        if self.min_sessions_for_submission_rate is None and "min_sessions_for_submission_rate" in self.model_fields_set:
            _dict['minSessionsForSubmissionRate'] = None

        # set to None if min_submission_rate_graduated (nullable) is None
        # and model_fields_set contains the field
        if self.min_submission_rate_graduated is None and "min_submission_rate_graduated" in self.model_fields_set:
            _dict['minSubmissionRateGraduated'] = None

        # set to None if random_admission_probability (nullable) is None
        # and model_fields_set contains the field
        if self.random_admission_probability is None and "random_admission_probability" in self.model_fields_set:
            _dict['randomAdmissionProbability'] = None

        # set to None if health (nullable) is None
        # and model_fields_set contains the field
        if self.health is None and "health" in self.model_fields_set:
            _dict['health'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetAudienceByIdEndpointOutput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "status": obj.get("status"),
            "qualifiedUserCount": obj.get("qualifiedUserCount"),
            "filters": [IAudienceFilter.from_dict(_item) for _item in obj["filters"]] if obj.get("filters") is not None else None,
            "logo": obj.get("logo"),
            "createdAt": obj.get("createdAt"),
            "ownerId": obj.get("ownerId"),
            "ownerMail": obj.get("ownerMail"),
            "organizationId": obj.get("organizationId"),
            "isPublic": obj.get("isPublic"),
            "isDistilling": obj.get("isDistilling"),
            "distillingCampaignId": obj.get("distillingCampaignId"),
            "minGraduatedForDistillingBoost": obj.get("minGraduatedForDistillingBoost"),
            "minDistillingForGlobalBoost": obj.get("minDistillingForGlobalBoost"),
            "graduationRule": IGraduationRule.from_dict(obj["graduationRule"]) if obj.get("graduationRule") is not None else None,
            "maxDistillingResponses": obj.get("maxDistillingResponses"),
            "dropMinResponses": obj.get("dropMinResponses"),
            "dropScore": obj.get("dropScore"),
            "maxDistillingSessions": obj.get("maxDistillingSessions"),
            "inactivityDropDays": obj.get("inactivityDropDays"),
            "minSubmissionRate": obj.get("minSubmissionRate"),
            "minSessionsForSubmissionRate": obj.get("minSessionsForSubmissionRate"),
            "minSubmissionRateGraduated": obj.get("minSubmissionRateGraduated"),
            "distillingRetrievalMode": obj.get("distillingRetrievalMode"),
            "boostLevel": obj.get("boostLevel"),
            "randomAdmissionProbability": obj.get("randomAdmissionProbability"),
            "health": obj.get("health"),
            "graduated": obj.get("graduated"),
            "dropped": obj.get("dropped")
        }
        try:
            _obj = cls.model_validate(_data)
        except ValidationError as _val_error:
            _obj = cls._lazy_construct(_data, _val_error)
        return _obj


