# coding: utf-8

"""
    Rapidata Asset API

    The API for the Rapidata Asset service

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from rapidata.api_client.models.billing_period_status_model import BillingPeriodStatusModel
from rapidata.api_client.models.i_line_item_model import ILineItemModel
from pydantic import ValidationError
from rapidata.api_client.lazy_model import LazyValidatedModel
from typing import Optional, Set
from typing_extensions import Self

class GetBillingPeriodOverviewEndpointOutput(LazyValidatedModel):
    """
    GetBillingPeriodOverviewEndpointOutput
    """ # noqa: E501
    id: StrictStr = Field(description="The billing period ID.")
    start_date: datetime = Field(description="The start date of the billing period.", alias="startDate")
    end_date: datetime = Field(description="The end date of the billing period.", alias="endDate")
    status: BillingPeriodStatusModel = Field(description="The status of the billing period.")
    total_gross_cost: Union[StrictFloat, StrictInt] = Field(description="The total gross cost before discounts.", alias="totalGrossCost")
    total_discount: Union[StrictFloat, StrictInt] = Field(description="The total discount amount.", alias="totalDiscount")
    total_net_cost: Union[StrictFloat, StrictInt] = Field(description="The total net cost after discounts.", alias="totalNetCost")
    total_response_count: StrictInt = Field(description="The total number of billable responses.", alias="totalResponseCount")
    line_items: List[ILineItemModel] = Field(alias="lineItems")
    __properties: ClassVar[List[str]] = ["id", "startDate", "endDate", "status", "totalGrossCost", "totalDiscount", "totalNetCost", "totalResponseCount", "lineItems"]

    # model_config is inherited from LazyValidatedModel


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetBillingPeriodOverviewEndpointOutput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in line_items (list)
        _items = []
        if self.line_items:
            for _item_line_items in self.line_items:
                if _item_line_items:
                    _items.append(_item_line_items.to_dict())
            _dict['lineItems'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetBillingPeriodOverviewEndpointOutput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "id": obj.get("id"),
            "startDate": obj.get("startDate"),
            "endDate": obj.get("endDate"),
            "status": obj.get("status"),
            "totalGrossCost": obj.get("totalGrossCost"),
            "totalDiscount": obj.get("totalDiscount"),
            "totalNetCost": obj.get("totalNetCost"),
            "totalResponseCount": obj.get("totalResponseCount"),
            "lineItems": [ILineItemModel.from_dict(_item) for _item in obj["lineItems"]] if obj.get("lineItems") is not None else None
        }
        try:
            _obj = cls.model_validate(_data)
        except ValidationError as _val_error:
            _obj = cls._lazy_construct(_data, _val_error)
        return _obj


