# coding: utf-8

"""
    Rapidata Asset API

    The API for the Rapidata Asset service

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from rapidata.api_client.models.i_asset_input_existing_asset_input import IAssetInputExistingAssetInput
from rapidata.api_client.models.i_asset_input_text_asset_input import IAssetInputTextAssetInput
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

IASSETINPUT_ONE_OF_SCHEMAS = ["IAssetInputExistingAssetInput", "IAssetInputMultiAssetInput", "IAssetInputTextAssetInput"]

class IAssetInput(BaseModel):
    """
    IAssetInput
    """
    # data type: IAssetInputExistingAssetInput
    oneof_schema_1_validator: Optional[IAssetInputExistingAssetInput] = None
    # data type: IAssetInputMultiAssetInput
    oneof_schema_2_validator: Optional[IAssetInputMultiAssetInput] = None
    # data type: IAssetInputTextAssetInput
    oneof_schema_3_validator: Optional[IAssetInputTextAssetInput] = None
    actual_instance: Optional[Union[IAssetInputExistingAssetInput, IAssetInputMultiAssetInput, IAssetInputTextAssetInput]] = None
    one_of_schemas: Set[str] = { "IAssetInputExistingAssetInput", "IAssetInputMultiAssetInput", "IAssetInputTextAssetInput" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = IAssetInput.model_construct()
        error_messages = []
        match = 0
        # validate data type: IAssetInputExistingAssetInput
        if not isinstance(v, IAssetInputExistingAssetInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `IAssetInputExistingAssetInput`")
        else:
            match += 1
        # validate data type: IAssetInputMultiAssetInput
        if not isinstance(v, IAssetInputMultiAssetInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `IAssetInputMultiAssetInput`")
        else:
            match += 1
        # validate data type: IAssetInputTextAssetInput
        if not isinstance(v, IAssetInputTextAssetInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `IAssetInputTextAssetInput`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in IAssetInput with oneOf schemas: IAssetInputExistingAssetInput, IAssetInputMultiAssetInput, IAssetInputTextAssetInput. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in IAssetInput with oneOf schemas: IAssetInputExistingAssetInput, IAssetInputMultiAssetInput, IAssetInputTextAssetInput. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into IAssetInputExistingAssetInput
        try:
            instance.actual_instance = IAssetInputExistingAssetInput.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into IAssetInputMultiAssetInput
        try:
            instance.actual_instance = IAssetInputMultiAssetInput.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into IAssetInputTextAssetInput
        try:
            instance.actual_instance = IAssetInputTextAssetInput.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into IAssetInput with oneOf schemas: IAssetInputExistingAssetInput, IAssetInputMultiAssetInput, IAssetInputTextAssetInput. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into IAssetInput with oneOf schemas: IAssetInputExistingAssetInput, IAssetInputMultiAssetInput, IAssetInputTextAssetInput. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], IAssetInputExistingAssetInput, IAssetInputMultiAssetInput, IAssetInputTextAssetInput]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())

from rapidata.api_client.models.i_asset_input_multi_asset_input import IAssetInputMultiAssetInput
# TODO: Rewrite to not use raise_errors
IAssetInput.model_rebuild(raise_errors=False)

