# coding: utf-8

"""
    Rapidata Asset API

    The API for the Rapidata Asset service

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from rapidata.api_client.models.i_pipeline_asset_pipeline_file_asset import IPipelineAssetPipelineFileAsset
from rapidata.api_client.models.i_pipeline_asset_pipeline_null_asset import IPipelineAssetPipelineNullAsset
from rapidata.api_client.models.i_pipeline_asset_pipeline_text_asset import IPipelineAssetPipelineTextAsset
from pydantic import StrictStr, Field
from rapidata.api_client.lazy_model import LazyValidatedModel
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

IPIPELINEASSET_ONE_OF_SCHEMAS = ["IPipelineAssetPipelineFileAsset", "IPipelineAssetPipelineMultiAsset", "IPipelineAssetPipelineNullAsset", "IPipelineAssetPipelineTextAsset"]

class IPipelineAsset(LazyValidatedModel):
    """
    IPipelineAsset
    """
    # data type: IPipelineAssetPipelineFileAsset
    oneof_schema_1_validator: Optional[IPipelineAssetPipelineFileAsset] = None
    # data type: IPipelineAssetPipelineMultiAsset
    oneof_schema_2_validator: Optional[IPipelineAssetPipelineMultiAsset] = None
    # data type: IPipelineAssetPipelineNullAsset
    oneof_schema_3_validator: Optional[IPipelineAssetPipelineNullAsset] = None
    # data type: IPipelineAssetPipelineTextAsset
    oneof_schema_4_validator: Optional[IPipelineAssetPipelineTextAsset] = None
    actual_instance: Optional[Union[IPipelineAssetPipelineFileAsset, IPipelineAssetPipelineMultiAsset, IPipelineAssetPipelineNullAsset, IPipelineAssetPipelineTextAsset]] = None
    one_of_schemas: Set[str] = { "IPipelineAssetPipelineFileAsset", "IPipelineAssetPipelineMultiAsset", "IPipelineAssetPipelineNullAsset", "IPipelineAssetPipelineTextAsset" }

    # model_config is inherited from LazyValidatedModel


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = IPipelineAsset.model_construct()
        error_messages = []
        match = 0
        # validate data type: IPipelineAssetPipelineFileAsset
        if not isinstance(v, IPipelineAssetPipelineFileAsset):
            error_messages.append(f"Error! Input type `{type(v)}` is not `IPipelineAssetPipelineFileAsset`")
        else:
            match += 1
        # validate data type: IPipelineAssetPipelineMultiAsset
        if not isinstance(v, IPipelineAssetPipelineMultiAsset):
            error_messages.append(f"Error! Input type `{type(v)}` is not `IPipelineAssetPipelineMultiAsset`")
        else:
            match += 1
        # validate data type: IPipelineAssetPipelineNullAsset
        if not isinstance(v, IPipelineAssetPipelineNullAsset):
            error_messages.append(f"Error! Input type `{type(v)}` is not `IPipelineAssetPipelineNullAsset`")
        else:
            match += 1
        # validate data type: IPipelineAssetPipelineTextAsset
        if not isinstance(v, IPipelineAssetPipelineTextAsset):
            error_messages.append(f"Error! Input type `{type(v)}` is not `IPipelineAssetPipelineTextAsset`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in IPipelineAsset with oneOf schemas: IPipelineAssetPipelineFileAsset, IPipelineAssetPipelineMultiAsset, IPipelineAssetPipelineNullAsset, IPipelineAssetPipelineTextAsset. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in IPipelineAsset with oneOf schemas: IPipelineAssetPipelineFileAsset, IPipelineAssetPipelineMultiAsset, IPipelineAssetPipelineNullAsset, IPipelineAssetPipelineTextAsset. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into IPipelineAssetPipelineFileAsset
        try:
            instance.actual_instance = IPipelineAssetPipelineFileAsset.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into IPipelineAssetPipelineMultiAsset
        try:
            instance.actual_instance = IPipelineAssetPipelineMultiAsset.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into IPipelineAssetPipelineNullAsset
        try:
            instance.actual_instance = IPipelineAssetPipelineNullAsset.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into IPipelineAssetPipelineTextAsset
        try:
            instance.actual_instance = IPipelineAssetPipelineTextAsset.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into IPipelineAsset with oneOf schemas: IPipelineAssetPipelineFileAsset, IPipelineAssetPipelineMultiAsset, IPipelineAssetPipelineNullAsset, IPipelineAssetPipelineTextAsset. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into IPipelineAsset with oneOf schemas: IPipelineAssetPipelineFileAsset, IPipelineAssetPipelineMultiAsset, IPipelineAssetPipelineNullAsset, IPipelineAssetPipelineTextAsset. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], IPipelineAssetPipelineFileAsset, IPipelineAssetPipelineMultiAsset, IPipelineAssetPipelineNullAsset, IPipelineAssetPipelineTextAsset]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())

from rapidata.api_client.models.i_pipeline_asset_pipeline_multi_asset import IPipelineAssetPipelineMultiAsset
# TODO: Rewrite to not use raise_errors
IPipelineAsset.model_rebuild(raise_errors=False)

