# coding: utf-8

"""
    Rapidata Asset API

    The API for the Rapidata Asset service

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from rapidata.api_client.models.i_pipeline_pair_maker_config_pipeline_full_permutation_pair_maker_config import IPipelinePairMakerConfigPipelineFullPermutationPairMakerConfig
from rapidata.api_client.models.i_pipeline_pair_maker_config_pipeline_online_pair_maker_config import IPipelinePairMakerConfigPipelineOnlinePairMakerConfig
from pydantic import StrictStr, Field
from rapidata.api_client.lazy_model import LazyValidatedModel
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

IPIPELINEPAIRMAKERCONFIG_ONE_OF_SCHEMAS = ["IPipelinePairMakerConfigPipelineFullPermutationPairMakerConfig", "IPipelinePairMakerConfigPipelineOnlinePairMakerConfig"]

class IPipelinePairMakerConfig(LazyValidatedModel):
    """
    IPipelinePairMakerConfig
    """
    # data type: IPipelinePairMakerConfigPipelineFullPermutationPairMakerConfig
    oneof_schema_1_validator: Optional[IPipelinePairMakerConfigPipelineFullPermutationPairMakerConfig] = None
    # data type: IPipelinePairMakerConfigPipelineOnlinePairMakerConfig
    oneof_schema_2_validator: Optional[IPipelinePairMakerConfigPipelineOnlinePairMakerConfig] = None
    actual_instance: Optional[Union[IPipelinePairMakerConfigPipelineFullPermutationPairMakerConfig, IPipelinePairMakerConfigPipelineOnlinePairMakerConfig]] = None
    one_of_schemas: Set[str] = { "IPipelinePairMakerConfigPipelineFullPermutationPairMakerConfig", "IPipelinePairMakerConfigPipelineOnlinePairMakerConfig" }

    # model_config is inherited from LazyValidatedModel


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = IPipelinePairMakerConfig.model_construct()
        error_messages = []
        match = 0
        # validate data type: IPipelinePairMakerConfigPipelineFullPermutationPairMakerConfig
        if not isinstance(v, IPipelinePairMakerConfigPipelineFullPermutationPairMakerConfig):
            error_messages.append(f"Error! Input type `{type(v)}` is not `IPipelinePairMakerConfigPipelineFullPermutationPairMakerConfig`")
        else:
            match += 1
        # validate data type: IPipelinePairMakerConfigPipelineOnlinePairMakerConfig
        if not isinstance(v, IPipelinePairMakerConfigPipelineOnlinePairMakerConfig):
            error_messages.append(f"Error! Input type `{type(v)}` is not `IPipelinePairMakerConfigPipelineOnlinePairMakerConfig`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in IPipelinePairMakerConfig with oneOf schemas: IPipelinePairMakerConfigPipelineFullPermutationPairMakerConfig, IPipelinePairMakerConfigPipelineOnlinePairMakerConfig. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in IPipelinePairMakerConfig with oneOf schemas: IPipelinePairMakerConfigPipelineFullPermutationPairMakerConfig, IPipelinePairMakerConfigPipelineOnlinePairMakerConfig. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into IPipelinePairMakerConfigPipelineFullPermutationPairMakerConfig
        try:
            instance.actual_instance = IPipelinePairMakerConfigPipelineFullPermutationPairMakerConfig.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into IPipelinePairMakerConfigPipelineOnlinePairMakerConfig
        try:
            instance.actual_instance = IPipelinePairMakerConfigPipelineOnlinePairMakerConfig.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into IPipelinePairMakerConfig with oneOf schemas: IPipelinePairMakerConfigPipelineFullPermutationPairMakerConfig, IPipelinePairMakerConfigPipelineOnlinePairMakerConfig. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into IPipelinePairMakerConfig with oneOf schemas: IPipelinePairMakerConfigPipelineFullPermutationPairMakerConfig, IPipelinePairMakerConfigPipelineOnlinePairMakerConfig. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], IPipelinePairMakerConfigPipelineFullPermutationPairMakerConfig, IPipelinePairMakerConfigPipelineOnlinePairMakerConfig]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


