# coding: utf-8

"""
    Rapidata.Dataset

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from rapidata.api_client.models.file_asset_input1 import FileAssetInput1
from rapidata.api_client.models.text_asset_input import TextAssetInput
from rapidata.api_client.models.url_asset_input import UrlAssetInput
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

MULTIASSETINPUT1ASSETSINNER_ONE_OF_SCHEMAS = ["FileAssetInput1", "MultiAssetInput1", "TextAssetInput", "UrlAssetInput"]

class MultiAssetInput1AssetsInner(BaseModel):
    """
    MultiAssetInput1AssetsInner
    """
    # data type: FileAssetInput1
    oneof_schema_1_validator: Optional[FileAssetInput1] = None
    # data type: MultiAssetInput1
    oneof_schema_2_validator: Optional[MultiAssetInput1] = None
    # data type: TextAssetInput
    oneof_schema_3_validator: Optional[TextAssetInput] = None
    # data type: UrlAssetInput
    oneof_schema_4_validator: Optional[UrlAssetInput] = None
    actual_instance: Optional[Union[FileAssetInput1, MultiAssetInput1, TextAssetInput, UrlAssetInput]] = None
    one_of_schemas: Set[str] = { "FileAssetInput1", "MultiAssetInput1", "TextAssetInput", "UrlAssetInput" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = MultiAssetInput1AssetsInner.model_construct()
        error_messages = []
        match = 0
        # validate data type: FileAssetInput1
        if not isinstance(v, FileAssetInput1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FileAssetInput1`")
        else:
            match += 1
        # validate data type: MultiAssetInput1
        if not isinstance(v, MultiAssetInput1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MultiAssetInput1`")
        else:
            match += 1
        # validate data type: TextAssetInput
        if not isinstance(v, TextAssetInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TextAssetInput`")
        else:
            match += 1
        # validate data type: UrlAssetInput
        if not isinstance(v, UrlAssetInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UrlAssetInput`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in MultiAssetInput1AssetsInner with oneOf schemas: FileAssetInput1, MultiAssetInput1, TextAssetInput, UrlAssetInput. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in MultiAssetInput1AssetsInner with oneOf schemas: FileAssetInput1, MultiAssetInput1, TextAssetInput, UrlAssetInput. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into FileAssetInput1
        try:
            instance.actual_instance = FileAssetInput1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into MultiAssetInput1
        try:
            instance.actual_instance = MultiAssetInput1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into TextAssetInput
        try:
            instance.actual_instance = TextAssetInput.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UrlAssetInput
        try:
            instance.actual_instance = UrlAssetInput.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into MultiAssetInput1AssetsInner with oneOf schemas: FileAssetInput1, MultiAssetInput1, TextAssetInput, UrlAssetInput. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into MultiAssetInput1AssetsInner with oneOf schemas: FileAssetInput1, MultiAssetInput1, TextAssetInput, UrlAssetInput. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], FileAssetInput1, MultiAssetInput1, TextAssetInput, UrlAssetInput]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())

from rapidata.api_client.models.multi_asset_input1 import MultiAssetInput1
# TODO: Rewrite to not use raise_errors
MultiAssetInput1AssetsInner.model_rebuild(raise_errors=False)

