# coding: utf-8

"""
    Rapidata Asset API

    The API for the Rapidata Asset service

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from rapidata.api_client.models.voucher_source import VoucherSource
from rapidata.api_client.models.voucher_status import VoucherStatus
from pydantic import ValidationError
from rapidata.api_client.lazy_model import LazyValidatedModel
from typing import Optional, Set
from typing_extensions import Self

class QueryVouchersEndpointOutput(LazyValidatedModel):
    """
    QueryVouchersEndpointOutput
    """ # noqa: E501
    id: StrictStr = Field(description="The voucher id.")
    amount: Union[StrictFloat, StrictInt] = Field(description="The face value of the voucher in dollars.")
    used: Union[StrictFloat, StrictInt] = Field(description="The amount already consumed across closed billing periods.")
    remaining: Union[StrictFloat, StrictInt] = Field(description="The remaining free usage the voucher can still grant.")
    issued_at: datetime = Field(description="When the voucher was issued.", alias="issuedAt")
    expires_at: datetime = Field(description="When the voucher expires.", alias="expiresAt")
    status: VoucherStatus = Field(description="The voucher's lifecycle status.")
    source: VoucherSource = Field(description="Where the voucher came from.")
    __properties: ClassVar[List[str]] = ["id", "amount", "used", "remaining", "issuedAt", "expiresAt", "status", "source"]

    # model_config is inherited from LazyValidatedModel


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QueryVouchersEndpointOutput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QueryVouchersEndpointOutput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "id": obj.get("id"),
            "amount": obj.get("amount"),
            "used": obj.get("used"),
            "remaining": obj.get("remaining"),
            "issuedAt": obj.get("issuedAt"),
            "expiresAt": obj.get("expiresAt"),
            "status": obj.get("status"),
            "source": obj.get("source")
        }
        try:
            _obj = cls.model_validate(_data)
        except ValidationError as _val_error:
            _obj = cls._lazy_construct(_data, _val_error)
        return _obj


