# coding: utf-8

"""
    Rapidata Asset API

    The API for the Rapidata Asset service

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from rapidata.api_client.models.run_status import RunStatus
from pydantic import ValidationError
from rapidata.api_client.lazy_model import LazyValidatedModel
from typing import Optional, Set
from typing_extensions import Self

class QueryLeaderboardRunsEndpointOutput(LazyValidatedModel):
    """
    QueryLeaderboardRunsEndpointOutput
    """ # noqa: E501
    id: StrictStr = Field(description="The unique identifier of the run.")
    name: StrictStr = Field(description="The name of the run.")
    status: RunStatus = Field(description="The status of the run.")
    created_at: datetime = Field(description="The timestamp when the run was created.", alias="createdAt")
    owner_mail: StrictStr = Field(description="The mail of the owner of the run.", alias="ownerMail")
    order_id: Optional[StrictStr] = Field(description="The id of the associated order, if any.", alias="orderId")
    __properties: ClassVar[List[str]] = ["id", "name", "status", "createdAt", "ownerMail", "orderId"]

    # model_config is inherited from LazyValidatedModel


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QueryLeaderboardRunsEndpointOutput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if order_id (nullable) is None
        # and model_fields_set contains the field
        if self.order_id is None and "order_id" in self.model_fields_set:
            _dict['orderId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QueryLeaderboardRunsEndpointOutput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "id": obj.get("id"),
            "name": obj.get("name"),
            "status": obj.get("status"),
            "createdAt": obj.get("createdAt"),
            "ownerMail": obj.get("ownerMail"),
            "orderId": obj.get("orderId")
        }
        try:
            _obj = cls.model_validate(_data)
        except ValidationError as _val_error:
            _obj = cls._lazy_construct(_data, _val_error)
        return _obj


