# coding: utf-8

"""
    Rapidata Asset API

    The API for the Rapidata Asset service

    The version of the OpenAPI document: 2026.07.24.1303-b3d1ec7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from rapidata.api_client.models.reconciliation_timestamp_mode import ReconciliationTimestampMode
from pydantic import ValidationError
from rapidata.api_client.lazy_model import LazyValidatedModel
from typing import Optional, Set
from typing_extensions import Self

class StartBulkReconciliationEndpointInput(LazyValidatedModel):
    """
    StartBulkReconciliationEndpointInput
    """ # noqa: E501
    billing_item_id: Optional[StrictStr] = Field(default=None, description="The identifier of a single billing item to reconcile.", alias="billingItemId")
    customer_id: Optional[UUID] = Field(default=None, description="The customer identifier to reconcile all billing items for.", alias="customerId")
    billing_group_id: Optional[StrictStr] = Field(default=None, description="The billing group identifier to reconcile all billing items for.", alias="billingGroupId")
    start_date: Optional[datetime] = Field(default=None, description="Optional start date filter. Only applies with CustomerId or BillingGroupId.", alias="startDate")
    end_date: Optional[datetime] = Field(default=None, description="Optional end date filter. Only applies with CustomerId or BillingGroupId.", alias="endDate")
    timestamp_mode: Optional[ReconciliationTimestampMode] = Field(default=None, description="Controls the timestamp used for correction entries.", alias="timestampMode")
    __properties: ClassVar[List[str]] = ["billingItemId", "customerId", "billingGroupId", "startDate", "endDate", "timestampMode"]

    # model_config is inherited from LazyValidatedModel


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StartBulkReconciliationEndpointInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if billing_item_id (nullable) is None
        # and model_fields_set contains the field
        if self.billing_item_id is None and "billing_item_id" in self.model_fields_set:
            _dict['billingItemId'] = None

        # set to None if customer_id (nullable) is None
        # and model_fields_set contains the field
        if self.customer_id is None and "customer_id" in self.model_fields_set:
            _dict['customerId'] = None

        # set to None if billing_group_id (nullable) is None
        # and model_fields_set contains the field
        if self.billing_group_id is None and "billing_group_id" in self.model_fields_set:
            _dict['billingGroupId'] = None

        # set to None if start_date (nullable) is None
        # and model_fields_set contains the field
        if self.start_date is None and "start_date" in self.model_fields_set:
            _dict['startDate'] = None

        # set to None if end_date (nullable) is None
        # and model_fields_set contains the field
        if self.end_date is None and "end_date" in self.model_fields_set:
            _dict['endDate'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StartBulkReconciliationEndpointInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "billingItemId": obj.get("billingItemId"),
            "customerId": obj.get("customerId"),
            "billingGroupId": obj.get("billingGroupId"),
            "startDate": obj.get("startDate"),
            "endDate": obj.get("endDate"),
            "timestampMode": obj.get("timestampMode")
        }
        try:
            _obj = cls.model_validate(_data)
        except ValidationError as _val_error:
            _obj = cls._lazy_construct(_data, _val_error)
        return _obj


